var mongoose = require('mongoose');

const AutoIncrement = require('mongoose-sequence')(mongoose);

var dataSchema = mongoose.Schema({
    firstName: String,
    lastName: String,
    parentOccupation: String,
    annualIncome: String,
    dob: String,
    placeofbirthwithdt: String,
    nationality: String,
    community: String,
    caste: String,
    scholarshipReq: String,
    motherTongue: String,
    physicallyChallenged: String,
    wardOfExServiceman: String,
    identificationMarks: String,
    hostelReq: String,
    collegeBusReq: String,
    maritalStatus: String,
    permanentAddress: String,
    permanentPincode: String,
    temporaryAddress: String,
    temporaryPincode: String,
    mobileNum: String,
    aadhaarNum: String,
    emailID: String,
    mobileNumParent: String,
    aadhaarNumParent: String,
    emailIDParent: String,
    bankAcNum: String,
    ifscCode: String,
    nameOfBank: String,
    nameOfSchool: String,
    mediumOfInstruction: String,
    distinctionInSports: String,
    part1: String,
    yearOfPassing1: String,
    regNo1: String,
    numAttempts1: String,
    maximumMarks1: String,
    marksObtained1: String,
    part2: String,
    yearOfPassing2: String,
    regNo2: String,
    numAttempts2: String,
    maximumMarks2: String,
    marksObtained2: String,
    part31: String,
    yearOfPassing31: String,
    regNo31: String,
    numAttempts31: String,
    maximumMarks31: String,
    marksObtained31: String,
    part32: String,
    yearOfPassing32: String,
    regNo32: String,
    numAttempts32: String,
    maximumMarks32: String,
    marksObtained32: String,
    part33: String,
    yearOfPassing33: String,
    regNo33: String,
    numAttempts33: String,
    maximumMarks33: String,
    marksObtained33: String,
    part34: String,
    yearOfPassing34: String,
    regNo34: String,
    numAttempts34: String,
    maximumMarks34: String,
    marksObtained34: String,
    maximumMarksTotal: String,
    marksObtainedTotal: String,
    hrSecCertNum: String,
    partILang: String,
    partIIITotal: String,
    partIIIPercentage: String,
    courseChoice1: String,
    courseChoice2: String
});

dataSchema.plugin(AutoIncrement, {inc_field: 'id'});

// Export Data model
var Data = module.exports = mongoose.model('data', dataSchema);
module.exports.get = function (callback, limit) {
    Data.find(callback).limit(limit);
}