var mongoose = require('mongoose');

var dataSchema = mongoose.Schema({
    ApplnNo:  { type: String, unique: true},
    Regno: String,
    firstName: String,
    lastName: String,
    MotherName:String,
    parentOccupation: String,
    MotherOccupation: String,
    annualIncome: String,
    dob: String,
    gender: { type: String, default: "Female" },
    placeofbirthwithdt: String,
    nationality: String,
    religion:String,
    community: String,
    caste: String,
    scholarshipReq: String,
    motherTongue: String,
    physicallyChallenged: String,
    physicallyChallengedrem: String,
    wardOfExServiceman: String,
    wardOfExServicemanrem:String,
    identificationMarks: String,
    hostelReq: String,
    collegeBusReq: String,
    maritalStatus: String,
    permanentAddress: String,
    permanentPincode: String,
    temporaryAddress: String,
    temporaryPincode: String,
    mobileNum: String,
    aadhaarNum: { type: Number, unique: true},
    aadhaarNumParent: String,
    emailID: String,
    mobileNumParent: String,
    bankAcNum: String,
    ifscCode: String,
    bankAcHolder: String,
    nameOfBank: String,
    nameOfBranch: String,
    nameOfSchool: String,
    BoardStudied: String,
    mediumOfInstruction: String,
    distinctionInSports: String,
    regNo: String,
    part1: String,
    yearOfPassing1: String,    
    numAttempts1: String,
    maximumMarks1: String,
    marksObtained1: String,
    part2: String,
    yearOfPassing2: String,
    numAttempts2: String,
    maximumMarks2: String,
    marksObtained2: String,
    part31: String,
    yearOfPassing31: String,
    numAttempts31: String,
    maximumMarks31: String,
    marksObtained31: String,
    part32: String,
    yearOfPassing32: String,
    numAttempts32: String,
    maximumMarks32: String,
    marksObtained32: String,
    part33: String,
    yearOfPassing33: String,
    numAttempts33: String,
    maximumMarks33: String,
    marksObtained33: String,
    part34: String,
    yearOfPassing34: String,
    numAttempts34: String,
    maximumMarks34: String,
    marksObtained34: String,
    maximumMarksTotal: String,
    marksObtainedTotal: String,
    Percentage: String,
    partIIITotal: String,
    partIIIPercentage: String,
    hrSecCertNum: String,
    certificateFile: String,
    Aadhaarcard: String,
    PassbookFile: String,
    partILang: String,
    LanguageChoice: String,     
    courseChoice1: String,
    courseChoice2: String,
    UGChoice: String,
    Interruptedstudies: String,
    Qualifiedexam: String,
    UGYOP: String,
    LastUniversity: String,
    studiedmaths: String,
    UGfeeconcession: String,
    DetailsFeeconcess: String,
    Extracurirepresent: String,
    DetailsExtracurirepresent:String,
    Talenthobbies: String,
    CNo: Number,
    coutype: String,
    Syear: Number,
    Academicyear: String,
    Admissionstatus: { type: String, default: " " },
    CNo: { type: Number, default: 0 },
    Course:  { type: String, default: " " },
    Section: { type: String, default: " " },
    Sem: { type: Number, default: 0 },
    SubmissionDate: { type: Date, default: Date.now },
    AdmissionDate: { type: Date, default: Date.now},
    Noofpaper: Number,
    TransferFrom:  { type: String, default: " " },
    TransferFromCNo:  { type: Number, default: 0 },
    DateOfTransfer: { type: String, default: " " },
    FromCourseTotal: { type: Number, default:0},
    ToCourseTotal:{ type: Number, default: 0},
    DiffAmount: { type: Number, default:0}

},{
    timestamps : true
});

// Export Data model
var Data = module.exports = mongoose.model('data', dataSchema);
module.exports.get = function (callback, limit) {
    Data.find(callback).limit(limit);
}